### ISSUE TITLE
Can't build after following quick start guide (fresh install)

### ISSUE THREAD

**Issue by Starwort** [NuclearPowered/Reactor.Template#2]
```  Reactor.OxygenFilter.MSBuild.props(33, 9): [MSB4062] The "LoadMappings" task could not be loaded from the assembly C:\Users\Starwort\.nuget\packages\reactor.oxygenfilter.msbuild\0.2.5\build\..\lib\netstandard2.1\Reactor.OxygenFilter.MSBuild.dll. Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.```
Following the quick start guide, got to here: https://docs.reactor.gg/docs/basic/compile_example_mod/
Built with rider, got this error
I haven't changed my csproj other than setting `        <TargetFramework>netstandard2.0</TargetFramework>` because the default 2.1 didn't work at all

**Comment by js6pak** [comment]
You are missing .net sdk (https://dotnet.microsoft.com/download/dotnet/5.0)

**Comment by Starwort** [comment]
I did install it, so that's weird. I'll try again this weekend
