### ISSUE TITLE
Minor Bug in TemplatePlugin.cs

### ISSUE THREAD

**Issue by Gekocaretaker** [NuclearPowered/Reactor.Template#5]
In the TemplatePlugin.cs file, at the bottom, in Postfix, the line __instance.nameText.Text should be __instance.nameText.text
Just a small bug, easily fixable, but could cause issues for people who don't know about small C# errors like this.

**Comment by Galster-dev** [comment]
Firstly, you always can PR and become a contributor.
Secondly, this template is outdated and is for game version 2021.3.31.3 (not sure about nuget tho), it was `Text` (because of `TextRenderer`) there
